version: '3.8'

networks:
  weatherapi:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - weatherapi
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - weatherapi

volumes:
  mysql_volume: